# Generated by Django 4.2.4 on 2023-09-03 21:47

from django.db import migrations, models
import hirestaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_link', models.URLField(validators=[hirestaurant.validators.validate_restaurant_list])),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('price_range', models.CharField(max_length=20)),
                ('restaurant_image1', models.ImageField(upload_to='restaurant_pics')),
                ('restaurant_image2', models.ImageField(upload_to='restaurant_pics')),
                ('restaurant_image3', models.ImageField(upload_to='restaurant_pics')),
            ],
        ),
    ]
