# Generated by Django 4.2.4 on 2023-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image2',
            field=models.ImageField(blank=True, upload_to='restaurant_pics'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image3',
            field=models.ImageField(blank=True, upload_to='restaurant_pics'),
        ),
    ]
