# Generated by Django 4.2.4 on 2023-09-06 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hirestaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0003_alter_restaurant_restaurant_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_link',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('restaurant_link', models.URLField(null=True, validators=[hirestaurant.validators.validate_restaurant_list])),
                ('content', models.TextField()),
                ('dt_created', models.DateField(auto_now_add=True)),
                ('dt_updated', models.DateField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('restaurant_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirestaurant.restaurant')),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
    ]
